######################################################################
# Automatically generated by qmake (2.00a) dim fév 12 17:25:55 2006
######################################################################

TEMPLATE = app
TARGET = jamqtplayer 
DEPENDPATH += . src src/qalf
INCLUDEPATH += . src/qalf
DESTDIR += bin
OBJECTS_DIR = obj

# Input
HEADERS += src/qalf/qalfmainwindow.h
SOURCES += src/jamqtplayer.cpp src/qalf/qalfmainwindow.cpp
